import type { Metadata } from "next";
import { Jost } from "next/font/google";
import AuthProviderHoc from "./components/sessionProvider/authProvider";
import "./sass/all.scss";

const jost = Jost({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "b2b Skynet",
  description: "Generated by Monema srl",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <AuthProviderHoc>
          <div className="mainWrapper">
            {children}
            <footer className="mainFooter">powered by Skynet</footer>
          </div>
        </AuthProviderHoc>
      </body>
    </html>
  );
}
