import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Jost } from "next/font/google";
import SessionProvider from "./components/sessionProvider/sessionProvider";

import SessionGuard from "./components/SessionGuard";
import "./sass/all.scss";

const jost = Jost({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "b2b Skynet",
  description: "Generated by Monema srl",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={jost.className}>
        <SessionProvider session={session} refetchInterval={4 * 60}>
          <SessionGuard>
            <div className="mainWrapper">
              {children}
              <footer className="mainFooter">powered by Skynet</footer>
            </div>
          </SessionGuard>

        </SessionProvider>
      </body>
    </html>
  );
}
